# Mid EXAM : Tools and Techniques Data Science 

# Task 1: ( 5 Marks)  Warp up 

# Note : Rename the file with your name and id and also mention your name and id inside here 

In [1]:
import numpy as np 

# Q1. Here, we take each element in the list a (temporarily assigning it the value i) 
a = [5, 10, 15, 20]

In [2]:
# (i)	Find the square each element in the list. This creates a new list called b and does not modify a through data comprehension.

In [3]:
b = list(map(lambda x:x**2,a))
print(b)


[25, 100, 225, 400]


In [4]:
# (ii)	Write a conditional statement of only squaring the elements if the element is not equal to 10.

filtered_result = list(map(lambda num: num ** 2 if num != 10 else num, a))
filtered_result = list(filter(lambda num: num != 10, filtered_result))
print(filtered_result)

[25, 225, 400]


In [5]:
# Q2. (i) Write the command of random samples from a uniform distribution between 0 and 1? 
random = np.random.uniform(0,1,size=(5,3))
random

array([[0.04712312, 0.17199756, 0.36169889],
       [0.33785671, 0.56916261, 0.93664757],
       [0.65453311, 0.77067822, 0.72562347],
       [0.01537359, 0.51038094, 0.02750365],
       [0.3459788 , 0.73430893, 0.06266412]])

In [6]:
import numpy as np 
import pandas as pd

In [7]:
np.linspace(0,5,num=5)

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [8]:
#(ii)	Write the command to slice the column 1? 
random[:1]

array([[0.04712312, 0.17199756, 0.36169889]])

In [9]:
#(iii)	Write the command of first and third elements in column 1?

In [10]:
random[:,1][1:4:2]

array([0.56916261, 0.51038094])

In [11]:
#(iv)	 Write the command of returns an 8 x 4 array

In [12]:
np.zeros((8,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
import pandas as pd 
import numpy as np

In [14]:
#Q3. Create a Series that looks like this below:
Flour     4 cups
Milk       1 cup
Eggs     2 large
Spam       1 can
Name: Dinner, dtype: object

SyntaxError: invalid syntax (4174055471.py, line 2)

In [ ]:
d = {'Flour':"4 Cups",'Milk':"1 Cup",'Eggs':"2 Large","Spam":"1 Can", "Name":"Dinner"}
pd.Series(d)

In [ ]:
# Q  4 Create the Data frame  as th output[27]

In [ ]:
sample = {"Apples":[35,41],"Bananas":[21,34]}
df = pd.DataFrame(sample,index=["2017Sales","2018Sales"])
df

In [ ]:
#Q4. create Dataframe then find imputation for these missing NaN in the out[47]

In [ ]:
data = {"Age":[23,39,45,np.NaN],"Gender":["M","F","F","M"],
        "Income":[24200.0,np.NaN,45390.0,np.NaN],
        "Religion":["Muslim","Christian",np.NaN,"Muslim"]}
df = pd.DataFrame(data)

In [ ]:
df

In [ ]:
#Q4(i)	Compute the appropriate missing value in income attribute?

In [ ]:
df["Income"].mean()

In [ ]:
#(ii)	Compute the appropriate missing values in religion attribute? 

In [ ]:
df["Religion"].mode()[0]

In [ ]:
#(iii)	Drop the columns where any of the elements is nan

In [ ]:
drop_col = df.dropna(axis=1)

In [ ]:
#(iv)	Keep only the rows with at least 2 non-na values

In [ ]:
df.dropna(thresh=2)